//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMovies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.MoviePaths = new HashSet<MoviePath>();
            this.MovieCasts = new HashSet<MovieCast>();
            this.MovieGenres = new HashSet<MovieGenre>();
        }
    
        public int Id { get; set; }
        public string ImdbId { get; set; }
        public string Name { get; set; }
        public string Runtime { get; set; }
        public string Released { get; set; }
    
        public virtual ICollection<MoviePath> MoviePaths { get; set; }
        public virtual ICollection<MovieCast> MovieCasts { get; set; }
        public virtual ICollection<MovieGenre> MovieGenres { get; set; }
    }
}
