//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMovies
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieGenre
    {
        public int Id { get; set; }
        public int Movies_Id { get; set; }
        public int Genre_ID { get; set; }
    }
}
