//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMovies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public Show()
        {
            this.Episodes = new HashSet<Episode>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string NewzbinSearch { get; set; }
    
        public virtual ICollection<Episode> Episodes { get; set; }
    }
}
